# File paths for data storage
items.file=src/main/resources/data/items.txt
users.file=src/main/resources/data/users.txt
transactions.file=src/main/resources/data/transactions.txt

# Thymeleaf settings
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# port
server.port=8080
